leaked_region.rs: stop leaking, and solve(?) crashes
bin/lst.rs:

  * keep a single global GlobalLeakedRegions around
  * replace 'static with lifetime parameters

leaked_region.rs:

  * replace 'static with lifetime parameters
  * own the storage in GlobalLeakedRegions; immediately add it when
    allocating a new region
  * do not clone InnerLeakedRegion anymore (is it UB?)
  * make min_region_size a runtime parameter; this allows for testing
    across multiple regions with Miri. And detect issues it does now.
  * make LeakedRegion.inner_leaked_region an Option to take it out in
    Drop (necessary for safety?)

All good except Miri thinks it's now not OK to deallocate the storage
(but it does work fine in practice):

    $ MIRIFLAGS='-Zmiri-tree-borrows' cargo +nightly miri run --bin test-leaked_region

    error: Undefined Behavior: deallocation through <9654> at alloc3787[0x0] is forbidden
        --> /home/coworking/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1887:17
         |
    1887 |                 self.1.deallocate(From::from(ptr.cast()), layout);
         |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
         |
         = help: this indicates a potential bug in the program: it performed an invalid operation, but the Tree Borrows rules it violated are still experimental
         = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/tree-borrows.md for further information
         = help: the accessed tag <9654> has state Disabled which forbids this deallocation (acting as a child write access)
    help: the accessed tag <9654> was created here, in the initial state Reserved
        --> src/leaked_region.rs:158:13
         |
     158 |             boxes.push(bx);
         |             ^^^^^^^^^^^^^^
    help: the accessed tag <9654> later transitioned to Disabled due to a foreign write access at offsets [0x0..0x12]
        --> src/leaked_region.rs:224:9
         |
     224 |         sl.copy_from_slice(bytes);
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^
         = help: this transition corresponds to a loss of read and write permissions
         = note: this is on thread `main`

This allows for testing across multiple regions with Miri. And detect issues it
does now.