lastitem: can we rely on b always being Some?
No, with an empty folder:

$ mkdir ba
$ RUST_BACKTRACE=1 ./lastfile --dirs ba
thread 'main' panicked at 'should always be Some?', src/bin/lastitem.rs:139:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:738:21
   6: lastitem::main::{{closure}}
             at /home/chrisrust/chj-rustbin/src/bin/lastitem.rs:139:31
   7: <rayon::iter::try_reduce::TryReduceFolder<R,T> as rayon::iter::plumbing::Folder<T>>::consume
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/try_reduce.rs:110:50
   8: <rayon::iter::try_fold::TryFoldFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::complete
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/try_fold.rs:159:9
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/plumbing/mod.rs:438:13
  10: rayon::iter::plumbing::bridge_producer_consumer
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/plumbing/mod.rs:397:12
  11: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/plumbing/mod.rs:373:13
  12: <rayon::vec::Drain<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/vec.rs:147:13
  13: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/vec.rs:83:9
  14: rayon::iter::plumbing::bridge
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/plumbing/mod.rs:357:12
  15: <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/vec.rs:58:9
  16: <rayon::iter::try_fold::TryFold<I,U,ID,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/try_fold.rs:66:9
  17: rayon::iter::try_reduce::try_reduce
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/try_reduce.rs:22:5
  18: rayon::iter::ParallelIterator::try_reduce
             at /home/chrisrust/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.5.3/src/iter/mod.rs:1070:9
  19: lastitem::main
             at /home/chrisrust/chj-rustbin/src/bin/lastitem.rs:126:9
  20: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5